CREATE TABLE estudiante (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(50) NOT NULL,

    apellido VARCHAR(50) NOT NULL,

    codigo_acceso VARCHAR(10) NOT NULL UNIQUE,

    fecha_nacimiento DATE NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    ultima_sesion TIMESTAMP,

    docente_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_estudiante_docente
        FOREIGN KEY (docente_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT

);

CREATE INDEX idx_estudiante_docente
ON estudiante(docente_id);