CREATE TABLE actividad (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(150) NOT NULL,

    descripcion TEXT NOT NULL,

    tipo_actividad VARCHAR(50) NOT NULL,

    dificultad VARCHAR(20) NOT NULL,

    configuracion JSONB NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    etapa_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_actividad_etapa
        FOREIGN KEY (etapa_id)
        REFERENCES etapa(id)
        ON DELETE RESTRICT

);

CREATE INDEX idx_actividad_etapa
ON actividad(etapa_id);